ui: mocha-bdd

browsers:
  - name: chrome
    version: [29, -5..latest]
  - name: safari
    version: -2..latest
  - name: firefox
    version: -5..latest
  - name: ie
    version: 9..latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: -1..latest
  - name: android
    version: -1..latest
  - name: iphone
    version: -1..latest
